import dgram from "node:dgram";
import { writeFile } from "node:fs/promises";
import http from "node:http";
import net from "node:net";
import { parseConfig } from "../../src/config/schema.js";
import { Engine } from "../../src/core/engine.js";
import { encodeSocksUdpPacket, parseSocksUdpPacket } from "../../src/inbound/socks5Udp.js";
import { closeSocket, makeDestination } from "../../src/utils/net.js";
import { readTestNetworkConfig } from "../../src/utils/testNetwork.js";

interface Sample { readonly atMs: number; readonly rss: number; readonly heapUsed: number }
const network = readTestNetworkConfig(); const args = process.argv.slice(2); const durationMs = readNumber("--duration-ms", Number(process.env.SEPIGS_SOAK_GATE_DURATION_MS ?? 1_800_000)); const concurrency = readNumber("--concurrency", 8); const dashboardToken = "beta-gate-dashboard-token";
const tcpEcho = await startTcpEcho(); const udpEcho = await startUdpEcho();
const rawConfig = { log: { level: "silent" }, limits: { connectTimeoutMs: 2_000, handshakeTimeoutMs: 2_000, idleTimeoutMs: 10_000, udpIdleTimeoutMs: 10_000, maxUdpSessions: 64 }, dns: { hosts: { "beta-fake.test": network.host }, fakeIp: { enabled: true, range: "198.18.0.0/24", size: 64, ttlSeconds: 600 } }, dashboard: { enabled: true, listen: network.host, port: 0, token: dashboardToken, rateLimitPerMinute: 100_000 }, inbounds: [{ type: "http", tag: "http", listen: network.host, port: 0 }, { type: "socks5", tag: "socks", listen: network.host, port: 0, udpAssociate: true }], outbounds: [{ type: "direct", tag: "direct" }, { type: "block", tag: "block" }], route: { defaultOutbound: "direct", rules: [{ port: [1], outboundTag: "block" }] } } as const;
const engine = new Engine(parseConfig(rawConfig)); await engine.start(); const httpPort = getPort(engine.getInboundAddress("http")); const socksPort = getPort(engine.getInboundAddress("socks")); const dashboardPort = getPort(engine.getDashboardAddress()); const fakeIp = await engine.allocateFakeIp("beta-fake.test");
let success = 0; let errors = 0; let reloads = 0; const errorReasons = new Map<string, number>(); const samples: Sample[] = []; const startedAt = Date.now();
const sampler = setInterval(() => { const memory = process.memoryUsage(); samples.push({ atMs: Date.now() - startedAt, rss: memory.rss, heapUsed: memory.heapUsed }); }, 60_000); sampler.unref();
let toggle = false; const reloader = setInterval(() => { toggle = !toggle; void engine.reloadConfig(parseConfig({ ...rawConfig, route: { defaultOutbound: "direct", rules: toggle ? [{ port: [1], outboundTag: "block" }] : [{ domain: ["never.invalid"], outboundTag: "block" }] } })).then(() => { reloads += 1; }, (error: unknown) => { recordError(withContext("reload", error)); }); }, 5_000); reloader.unref();
try {
  await Promise.all(Array.from({ length: concurrency }, async (_value, worker) => { while (Date.now() - startedAt < durationMs) { const mode = worker % 6; try { if (mode === 0) await httpTunnel(httpPort, network.host, tcpEcho.port, "http"); else if (mode === 1) await socksTunnel(socksPort, tcpEcho.port); else if (mode === 2) await socksUdp(socksPort, udpEcho.port); else if (mode === 3) await httpTunnel(httpPort, fakeIp, tcpEcho.port, "fake"); else if (mode === 4) await dashboardMetrics(dashboardPort); else await blocked(httpPort); success += 1; } catch (error) { recordError(withContext(modeName(mode), error)); } await sleep(25); } }));
} finally { clearInterval(sampler); clearInterval(reloader); await engine.stop(); await tcpEcho.close(); await udpEcho.close(); }
const total = success + errors; const errorRate = total === 0 ? 1 : errors / total; const leaks = engine.getLeakSnapshot(); const passed = errorRate < 0.001 && leaks.activeSockets === 0 && leaks.activeTimers === 0 && leaks.activeListeners === 0;
const memory = process.memoryUsage(); const report = ["# v0.2.0-beta Soak Gate", "", `- Duration ms: ${durationMs}`, `- Concurrency: ${concurrency}`, `- Success: ${success}`, `- Errors: ${errors}`, `- Error rate: ${errorRate}`, `- Error reasons: ${JSON.stringify(Object.fromEntries(errorReasons))}`, `- Reloads: ${reloads}`, `- UDP packets upload/download: ${engine.getStats().udpPacketsClientToRemote}/${engine.getStats().udpPacketsRemoteToClient}`, `- Fake-IP assignments: ${engine.getStats().fakeIpAssignmentsTotal ?? 0}`, `- Dashboard requests/errors: ${engine.getStats().dashboardRequestsTotal ?? 0}/${engine.getStats().dashboardErrorsTotal ?? 0}`, `- Final sockets/timers/listeners: ${leaks.activeSockets}/${leaks.activeTimers}/${leaks.activeListeners}`, `- Final RSS/heap MiB: ${(memory.rss / 1_048_576).toFixed(2)}/${(memory.heapUsed / 1_048_576).toFixed(2)}`, `- Samples: ${samples.length}`, `- Gate: ${passed ? "passed" : "failed"}`, ""].join("\n"); await writeFile("docs/soak-v0.2.0-beta-report.md", report, "utf8"); console.log(`beta soak gate ${passed ? "passed" : "failed"}: success=${success} errors=${errors} rate=${errorRate}`); if (!passed) process.exitCode = 1;

function recordError(error: unknown): void { errors += 1; const reason = error instanceof Error ? error.message : String(error); errorReasons.set(reason, (errorReasons.get(reason) ?? 0) + 1); }
function withContext(context: string, error: unknown): Error { return new Error(`${context}: ${error instanceof Error ? error.message : String(error)}`); }
function modeName(mode: number): string { return ["http-connect", "socks5-connect", "socks5-udp", "fake-ip-connect", "dashboard-metrics", "block-route"][mode] ?? `worker-${mode}`; }
async function httpTunnel(proxyPort: number, host: string, targetPort: number, payload: string): Promise<void> { const socket = await connect(proxyPort); try { socket.write(`CONNECT ${host}:${targetPort} HTTP/1.1\r\nHost: ${host}:${targetPort}\r\n\r\n`); await readUntil(socket, (data) => data.includes("200 Connection Established")); socket.write(payload); await readUntil(socket, (data) => data.includes(payload)); } finally { closeSocket(socket); } }
async function socksTunnel(proxyPort: number, targetPort: number): Promise<void> { const socket = await connect(proxyPort); try { socket.write(Buffer.from([5, 1, 0])); await readUntil(socket, (data) => data.byteLength >= 2); const host = Buffer.from(network.host); socket.write(Buffer.concat([Buffer.from([5, 1, 0, 3, host.byteLength]), host, Buffer.from([(targetPort >> 8) & 0xff, targetPort & 0xff])])); await readUntil(socket, (data) => data.byteLength >= 10); socket.write("socks"); await readUntil(socket, (data) => data.includes("socks")); } finally { closeSocket(socket); } }
async function socksUdp(proxyPort: number, targetPort: number): Promise<void> { const control = await connect(proxyPort); const udp = dgram.createSocket("udp4"); try { control.write(Buffer.from([5, 1, 0])); await readUntil(control, (data) => data.byteLength >= 2); control.write(Buffer.from([5, 3, 0, 1, 0, 0, 0, 0, 0, 0])); const reply = await readUntil(control, (data) => data.byteLength >= 10); const relayPort = ((reply[8] ?? 0) << 8) + (reply[9] ?? 0); const payload = Buffer.from("udp"); const response = parseSocksUdpPacket(await udpExchange(udp, relayPort, encodeSocksUdpPacket(makeDestination(network.host, targetPort), payload))); if (!response.payload.equals(payload)) throw new Error("UDP mismatch"); } finally { control.destroy(); udp.close(); } }
async function blocked(proxyPort: number): Promise<void> { const socket = await connect(proxyPort); try { socket.write(`CONNECT ${network.host}:1 HTTP/1.1\r\nHost: ${network.host}:1\r\n\r\n`); const response = await readUntil(socket, (data) => data.includes("\r\n\r\n")); if (!response.includes("403") && !response.includes("502")) throw new Error("block route did not reject"); } finally { closeSocket(socket); } }
async function dashboardMetrics(port: number): Promise<void> { await new Promise<void>((resolve, reject) => { const request = http.request({ host: network.host, port, path: "/api/metrics", headers: { authorization: `Bearer ${dashboardToken}` } }, (response) => { const chunks: Buffer[] = []; response.on("data", (chunk: Buffer) => chunks.push(chunk)); response.on("end", () => { const body = Buffer.concat(chunks).toString(); if (response.statusCode === 200 && body.includes("sepigs_uptime_seconds")) resolve(); else reject(new Error("Dashboard metrics response invalid")); }); }); request.setTimeout(5_000, () => request.destroy(new Error("request timeout"))); request.once("error", reject); request.end(); }); }
async function connect(port: number): Promise<net.Socket> { return await new Promise((resolve, reject) => { const socket = net.createConnection({ host: network.host, port }); const timer = setTimeout(() => socket.destroy(new Error("connect timeout")), 5_000); const cleanup = (): void => { clearTimeout(timer); socket.removeListener("connect", onConnect); socket.removeListener("error", onError); }; const onConnect = (): void => { cleanup(); resolve(socket); }; const onError = (error: Error): void => { cleanup(); reject(error); }; socket.once("connect", onConnect); socket.once("error", onError); }); }
async function readUntil(socket: net.Socket, predicate: (data: Buffer) => boolean): Promise<Buffer> { return await new Promise((resolve, reject) => { let data = Buffer.alloc(0); const timer = setTimeout(() => { cleanup(); reject(new Error("read timeout")); }, 5_000); const cleanup = (): void => { clearTimeout(timer); socket.removeListener("data", onData); socket.removeListener("error", onError); }; const onError = (error: Error): void => { cleanup(); reject(error); }; const onData = (chunk: Buffer): void => { data = Buffer.concat([data, chunk]); if (predicate(data)) { cleanup(); resolve(data); } }; socket.on("data", onData); socket.once("error", onError); }); }
async function udpExchange(socket: dgram.Socket, port: number, packet: Buffer): Promise<Buffer> { return await new Promise((resolve, reject) => { const timer = setTimeout(() => { cleanup(); reject(new Error("UDP timeout")); }, 5_000); const cleanup = (): void => { clearTimeout(timer); socket.removeListener("message", onMessage); socket.removeListener("error", onError); }; const onMessage = (message: Buffer): void => { cleanup(); resolve(message); }; const onError = (error: Error): void => { cleanup(); reject(error); }; socket.once("message", onMessage); socket.once("error", onError); socket.send(packet, port, network.host); }); }
async function startTcpEcho(): Promise<{ port: number; close(): Promise<void> }> { const server = net.createServer((socket) => { socket.on("error", () => undefined); socket.pipe(socket); }); await new Promise<void>((resolve, reject) => { server.once("error", reject); server.listen(network.port, network.host, resolve); }); return { port: getPort(server.address()), close: async () => { await new Promise<void>((resolve) => server.close(() => { resolve(); })); } }; }
async function startUdpEcho(): Promise<{ port: number; close(): Promise<void> }> { const socket = dgram.createSocket("udp4"); socket.on("message", (message, rinfo) => { socket.send(message, rinfo.port, rinfo.address); }); await new Promise<void>((resolve, reject) => { socket.once("error", reject); socket.bind(0, network.host, resolve); }); return { port: socket.address().port, close: async () => { await new Promise<void>((resolve) => socket.close(() => { resolve(); })); } }; }
function getPort(address: net.AddressInfo | string | null): number { if (typeof address === "object" && address !== null) return address.port; throw new Error("expected address"); }
function readNumber(name: string, fallback: number): number { const index = args.indexOf(name); const value = Number(index < 0 ? fallback : args[index + 1]); if (!Number.isInteger(value) || value < 1) throw new Error(`${name} must be positive`); return value; }
async function sleep(ms: number): Promise<void> { await new Promise((resolve) => setTimeout(resolve, ms)); }
