[General]
loglevel = notify
allow-wifi-access = false

[Proxy]
sepigs-http = http, 127.0.0.1, 8080
sepigs-socks = socks5, 127.0.0.1, 1080

[Proxy Group]
SEPIGS = select, sepigs-http, sepigs-socks, DIRECT

[Rule]
FINAL,SEPIGS
